import { FullPortfolioData } from "./types";

export const defaultPortfolioData: FullPortfolioData = {
  hero: {
    id: "default-hero",
    name: "Monu Gupta",
    title: "Full-Stack Developer • Data Analyst • AI & ML Solutions",
    tagline: "Crafting luxury 3D interfaces, liquid glass aesthetics, and intelligent digital instruments.",
    availabilityTag: "Available for Development & Data Projects",
    showAvailabilityTag: true,
    showIdentitySubtitle: true,
    headlinePrefix: "Turning Ideas",
    headlineGradient: "Into Elegant",
    headlineSuffix: "Digital Solutions.",
    bio: "I create modern websites, scalable applications, interactive dashboards, and intelligent data solutions by combining software engineering, analytics, and machine learning.",
    primaryCtaText: "View My Work",
    primaryCtaLink: "#projects",
    secondaryCtaText: "Let's Connect",
    secondaryCtaLink: "#contact",
    githubUrl: "https://github.com",
    linkedinUrl: "https://linkedin.com",
    twitterUrl: "https://x.com",
    email: "contact@monugupta.design",
    avatarUrl: "/images/personal/cube-front.png",
    showStats: true,
    stats: [
      { id: "stat-1", value: "6+", label: "Years Craft", color: "text-white" },
      { id: "stat-2", value: "120 FPS", label: "Native WebGL", color: "text-cyan-400" },
      { id: "stat-3", value: "99+", label: "Lighthouse", color: "text-white" },
      { id: "stat-4", value: "VisionOS", label: "Spatial UI", color: "text-indigo-400" },
    ],
    cubeFrontImg: "/images/personal/cube-front.png",
    cubeRightImg: "/images/personal/cube-creative.png",
    cubeBackImg: "/images/personal/cube-lifestyle.png",
    cubeLeftImg: "/images/personal/cube-code.png",
    cubeTopImg: "/images/personal/cube-studio.png",
    cubeBottomImg: "/images/personal/cube-front.png",

    // Contact / Enquiry Section Controls
    contactBadge: "INITIATE COLLABORATION",
    contactHeadingPrefix: "Let’s Build",
    contactHeadingGradient: "Something Visionary.",
    contactSubtitle: "Available for bespoke WebGL installations, spatial UX architecture, advisory roles, and high-impact engineering projects.",
    contactDirectEmailLabel: "Direct Email",
    contactFormTitle: "Send a Message",
    contactFormSubtitle: "Have a project in mind, a question, or a collaboration opportunity? Reach out anytime.",
    contactSubmitButtonText: "Send Message",
    showGithubLink: true,
    showLinkedinLink: true,
    showTwitterLink: true,
  },
  projects: [
    {
      id: "proj-1",
      title: "Aura VisionOS Workspace",
      slug: "aura-visionos-workspace",
      subtitle: "Immersive spatial computing canvas with liquid refractive windows & gaze physics",
      category: "Spatial UI",
      status: "Production",
      featured: true,
      order: 1,
      thumbnail: "/images/projects/spatial-vision-os.jpg",
      gallery: [
        "/images/projects/spatial-vision-os.jpg",
        "/images/personal/cube-creative.png",
      ],
      videoUrl: null,
      techStack: ["Next.js", "Three.js", "WebXR", "GSAP", "Tailwind CSS"],
      problem: "Traditional flat user interfaces fail to convey the tangible depth, optical realism, and tactile materiality required for next-generation spatial computing operating systems.",
      solution: "Engineered a custom liquid glass shader pipeline with real-time multi-layered refraction, chromatic dispersion, specular edge highlights, and spatial gaze-tracking physics.",
      architecture: "Custom WebGL GLSL fragment shaders running at 120 FPS on Apple Vision Pro and modern Chromium browsers, paired with adaptive WebXR compositor fallbacks.",
      impact: "Featured across top WebGL showcases; scored 99+ on Lighthouse Performance benchmarks with sub-8ms frame render times.",
      performance: "120 FPS Native • 4.2MB Bundle • 0.1s TTI",
      liveUrl: "https://example.com/demo/aura",
      githubUrl: "https://github.com/example/aura-visionos",
    },
    {
      id: "proj-2",
      title: "Synapse Neural Flow Engine",
      slug: "synapse-neural-flow",
      subtitle: "Real-time 3D synaptic knowledge graph and vector embedding visualizer",
      category: "AI / Data",
      status: "Production",
      featured: true,
      order: 2,
      thumbnail: "/images/projects/neural-ai-engine.jpg",
      gallery: [
        "/images/projects/neural-ai-engine.jpg",
        "/images/personal/cube-code.png",
      ],
      videoUrl: null,
      techStack: ["React", "Three.js", "Python", "FastAPI", "WebSockets"],
      problem: "Visualizing high-dimensional LLM embeddings and 3.8M synaptic weights in real time without locking the browser UI thread.",
      solution: "Implemented GPU instanced buffer geometries with Barnes-Hut force-directed simulation executed in Web Workers with binary WebSocket streaming.",
      architecture: "Python backend streaming sparse vector graph deltas to WebGL instanced mesh renderers with automatic occlusion culling.",
      impact: "Processes 100k+ concurrent active nodes with sub-1.2ms latency and zero garbage collection pauses.",
      performance: "100k Nodes • 1.2ms Latency • 60 FPS Solid",
      liveUrl: "https://example.com/demo/synapse",
      githubUrl: "https://github.com/example/synapse-engine",
    },
    {
      id: "proj-3",
      title: "Liquid Caustics Shader Studio",
      slug: "liquid-caustics-shader",
      subtitle: "Procedural liquid metal and optical crystal refractive physics playground",
      category: "3D / WebGL",
      status: "Experimental",
      featured: true,
      order: 3,
      thumbnail: "/images/projects/liquid-physics-shader.jpg",
      gallery: [
        "/images/projects/liquid-physics-shader.jpg",
        "/images/personal/cube-studio.png",
      ],
      videoUrl: null,
      techStack: ["Three.js", "GLSL Shaders", "React Three Fiber", "WebAudio API"],
      problem: "Simulating physically accurate light caustics and viscous fluid inertia at interactive frame rates on mobile and low-tier GPUs.",
      solution: "Developed dual-pass screen-space refraction shaders combined with Verlet integration fluid particles and audio-reactive frequency modulators.",
      architecture: "Modular R3F shader material nodes with adaptive Level of Detail (LOD) and dynamic DPR throttling on mobile screens.",
      impact: "Downloaded and starred by 4,000+ creative developers; adopted into multiple commercial creative coding systems.",
      performance: "Dual-Pass Caustics • 60 FPS Mobile • Zero Stutter",
      liveUrl: "https://example.com/demo/liquid",
      githubUrl: "https://github.com/example/liquid-caustics",
    },
    {
      id: "proj-4",
      title: "Quantum Glass Fintech Terminal",
      slug: "quantum-glass-fintech",
      subtitle: "Ultra-low latency institutional crypto and algorithmic trading workstation",
      category: "Full Stack",
      status: "Production",
      featured: true,
      order: 4,
      thumbnail: "/images/projects/quantum-fintech.jpg",
      gallery: [
        "/images/projects/quantum-fintech.jpg",
        "/images/personal/cube-lifestyle.png",
      ],
      videoUrl: null,
      techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Rust WASM", "ECharts"],
      problem: "Financial trading dashboards are typically cluttered, visually aggressive, and choke on high-frequency order book bursts.",
      solution: "Engineered an Apple-grade dark glass aesthetic with micro-level depth layering and Rust WebAssembly order book aggregation.",
      architecture: "Rust WASM processing 50k ticks/sec with delta updates piped to offscreen canvas chart renderers.",
      impact: "Adopted by institutional algorithmic trading desks; reduced client CPU utilization by 74% compared to legacy solutions.",
      performance: "50k ticks/sec • 74% Less CPU • 0ms UI lag",
      liveUrl: "https://example.com/demo/quantum",
      githubUrl: "https://github.com/example/quantum-fintech",
    },
  ],
  skills: [
    { id: "sk-1", name: "Three.js & WebGL", category: "Frontend & 3D", level: 96, icon: "Box", order: 1, highlight: true, description: "Custom GLSL Shaders, R3F, Post-processing, 3D Physics" },
    { id: "sk-2", name: "React & Next.js (App Router)", category: "Frontend & 3D", level: 98, icon: "Atom", order: 2, highlight: true, description: "Server Components, Suspense, State Architecture, Edge API" },
    { id: "sk-3", name: "TypeScript", category: "Frontend & 3D", level: 95, icon: "Code", order: 3, highlight: false, description: "Strict Type Systems, Generics, AST tooling" },
    { id: "sk-4", name: "GSAP & Framer Motion", category: "Frontend & 3D", level: 94, icon: "Zap", order: 4, highlight: true, description: "Physics-based spring animation, ScrollTriggers, Morphing" },
    { id: "sk-5", name: "Node.js & Express", category: "Backend & Cloud", level: 90, icon: "Server", order: 5, highlight: false, description: "Microservices, WebSockets, REST & GraphQL APIs" },
    { id: "sk-6", name: "PostgreSQL & SQLite (Prisma)", category: "Backend & Cloud", level: 92, icon: "Database", order: 6, highlight: true, description: "Schema Design, Query Optimization, Atomic Transactions" },
    { id: "sk-7", name: "Python & Data Science", category: "AI & Data", level: 88, icon: "Cpu", order: 7, highlight: false, description: "Vector Embeddings, PyTorch, NumPy, Data Pipelines" },
    { id: "sk-8", name: "AI Agent & LLM Orchestration", category: "AI & Data", level: 92, icon: "Sparkles", order: 8, highlight: true, description: "RAG architectures, Function Calling, Prompt Engineering" },
    { id: "sk-9", name: "Apple VisionOS / Spatial UI", category: "Spatial & Design", level: 95, icon: "Eye", order: 9, highlight: true, description: "Glassmorphism, Depth Layering, Material Design, Gaze UI" },
    { id: "sk-10", name: "Figma & 3D Product Design", category: "Spatial & Design", level: 91, icon: "Palette", order: 10, highlight: false, description: "Design Systems, Micro-interactions, Motion Prototyping" },
  ],
  experience: [
    {
      id: "exp-1",
      role: "Lead Creative Technologist & 3D Architect",
      company: "Aether Spatial Labs",
      location: "San Francisco, CA (Remote)",
      period: "2024 — Present",
      type: "Full-time",
      order: 1,
      description: "Leading the development of next-generation spatial computing interfaces, WebGL graphic pipelines, and flagship design systems for high-growth digital products.",
      achievements: [
        "Architected proprietary WebGL/WebXR liquid glass shader system powering 4 enterprise spatial apps.",
        "Improved rendering performance by 65% across mobile devices through instanced buffer geometry.",
        "Spearheaded the design system combining VisionOS depth paradigms with accessible web standards.",
      ],
      technologies: ["Three.js", "WebXR", "Next.js", "GLSL", "TypeScript", "Tailwind CSS"],
    },
    {
      id: "exp-2",
      role: "Senior Frontend Engineer & Interactive Designer",
      company: "Kinetic Digital Studio",
      location: "New York, NY",
      period: "2022 — 2024",
      type: "Full-time",
      order: 2,
      description: "Crafted award-winning interactive digital experiences, cinematic 3D product launches, and fluid web applications for global luxury brands.",
      achievements: [
        "Delivered 12+ custom WebGL/GSAP interactive websites winning 6 Awwwards & FWA recognitions.",
        "Built ultra-smooth Lenis-driven physics scroll engines with adaptive mobile fallbacks.",
        "Mentored a team of 6 engineers on 3D mathematical matrices, shaders, and React performance.",
      ],
      technologies: ["React", "GSAP", "Three.js", "Framer Motion", "WebGL", "Node.js"],
    },
    {
      id: "exp-3",
      role: "Full Stack & Creative Engineering Resident",
      company: "Horizon Interactive",
      location: "Seattle, WA",
      period: "2021 — 2022",
      type: "Contract",
      order: 3,
      description: "Engineered scalable web applications, real-time analytics dashboards, and interactive data visualizations.",
      achievements: [
        "Developed high-throughput data visualizer handling millions of streaming data points.",
        "Created reusable glassmorphism UI kit adopted across all internal product tools.",
      ],
      technologies: ["TypeScript", "Next.js", "Python", "PostgreSQL", "Docker"],
    },
    {
      id: "exp-4",
      role: "B.S. in Computer Science & Interactive Media",
      company: "Institute of Technology",
      location: "Honors Graduate",
      period: "2017 — 2021",
      type: "Education",
      order: 4,
      description: "Concentration in Computer Graphics, Human-Computer Interaction (HCI), Real-Time Systems, and Distributed Computing.",
      achievements: [
        "Published undergraduate paper on real-time screen-space fluid caustics in WebGL.",
        "Winner of National Creative Computing Hackathon (Grand Prize).",
      ],
      technologies: ["Computer Graphics", "C++", "OpenGL", "Algorithms", "HCI"],
    },
  ],
  about: {
    id: "default-about",
    badge: "ORIGIN & PHILOSOPHY",
    titlePrefix: "My",
    titleGradient: "Journey",
    subtitle: "A relentless pursuit of technical excellence, spatial aesthetics, and physical digital craftsmanship.",
    storyTitle: "Code as a Sculptural Medium",
    showStoryTitle: true,
    storyParagraph1: "I view code not merely as a set of logical instructions, but as a sculptural, fluid medium. My journey started at the intersection of computer graphics and human psychology — exploring how light, physical inertia, and spatial depth can transform passive software into an evocative, unforgettable tactile experience.",
    showStoryParagraph1: true,
    storyParagraph2: "Over the past 6+ years, I have dedicated myself to engineering digital products that feel physical, touchable, and effortlessly smooth. Whether crafting an Apple VisionOS-level spatial interface, optimizing complex WebGL shader pipelines, or architecting intelligent AI-driven systems, my philosophy remains constant: uncompromising performance wrapped in timeless luxury minimalism.",
    showStoryParagraph2: true,
    additionalParagraphs: [],
    showHardwareSpecs: true,
    hardwareTitle: "Studio Environment & Instruments",
    hardwareSpecs: [
      { label: "Primary Rig", value: "Apple Silicon M3 Max (128GB Unified Memory)" },
      { label: "Display", value: "Apple Pro Display XDR 32-inch 6K Retinal" },
      { label: "Spatial Device", value: "Apple Vision Pro 512GB (visionOS 2.0)" },
      { label: "Creative Stack", value: "VS Code, Three.js, Blender, Figma, Warp Terminal" },
    ],
    showPhotoCard: true,
    photoUrl: "/images/personal/cube-front.png",
    photoOverlayTag: "Spatial Technologist",
    photoOverlayName: "Monu Gupta",
    showPhilosophy: true,
    philosophyTitle: "Engineering & Design Principles",
    philosophyText: "Every element must serve an intentional purpose. I focus on creating clean, intuitive user experiences backed by robust architectures, fluid interactions, and deep structural elegance.",
    coreValues: [
      { title: "Physicality & Spatial Depth", desc: "Digital interfaces should behave with the physical weight, optical refractions, and tactile feedback of high-end physical instruments." },
      { title: "Performance as a Foundation", desc: "I prioritize high-performance engineering, ensuring smooth, responsive, and seamless experiences across all devices and screen sizes." },
      { title: "Micro-Craftsmanship", desc: "From subtle specular borders to custom spring easing curves, perfection lives in the sub-pixel details." },
      { title: "Intelligence & Purpose", desc: "Applying modern machine learning models and intelligent data processing to build practical, high-impact digital solutions." },
    ],
  },
  settings: {
    id: "default-settings",
    siteTitle: "Monu Gupta — Full-Stack Developer • Data Analyst • AI & ML Solutions",
    metaDesc: "Portfolio of Monu Gupta — Full-Stack Developer, Data Analyst, and AI/ML Specialist building high-performance web applications, analytics dashboards, and intelligent software.",
    ogImageUrl: "/images/projects/spatial-vision-os.jpg",
    accentColor: "#38bdf8",
    analyticsEnabled: true,
    // Header / Navbar
    headerMonogram: "MG",
    showHeaderCmsLink: true,
    navItems: [
      { id: "home", label: "Home", href: "#home", visible: true, icon: "Sparkles" },
      { id: "projects", label: "Projects", href: "#projects", visible: true, icon: "Layers" },
      { id: "skills", label: "Skills", href: "#skills", visible: true, icon: "Terminal" },
      { id: "experience", label: "Experience", href: "#experience", visible: true, icon: "Briefcase" },
      { id: "about", label: "About", href: "#about", visible: true, icon: "User" },
      { id: "contact", label: "Contact", href: "#contact", visible: true, icon: "Mail" },
    ],
    // Footer
    showFooter: true,
    footerMonogram: "MG",
    footerName: "Monu Gupta",
    footerCopyright: "© 2026 • All Rights Reserved",
    footerStatusTag: "Spatial Engine 2.0",
    showLiveClock: true,
    showBackToTop: true,
    footerLinks: [],
    // Asset Protection & Screenshot Security Defaults
    blockScreenshots: true,
    disableRightClick: true,
    disableMediaSave: true,
  },
};

